---

- name: '[KS VARS][MAIN] Load variables from files'
  include_vars:
    dir: '../vars'

- name: "[KSVALIDATE MAIN] Preliminary checks"
  import_tasks: 'prerequisites.yml'

- name: "[KSVALIDATE MAIN] Create Container"
  import_tasks: 'container.yml'

- name: "[KSVALIDATE MAIN] Mount kickstart"
  import_tasks: 'mount_ks.yml'

- name: "[KSVALIDATE MAIN] Post Validate"
  import_tasks: 'post-validate.yml'

